# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://kolya-ya.github.io/RMD/"
# baseURL = "http://localhost:1313/"
title = "RMD - New theme RMD Bau"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
enableEmoji = true
theme = "rmd-theme"

paginate = 3              # Number of articles displayed on the homepage
rssLimit = 20             # Limit Entry Count to Rss file
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = "RMD Bau City"            # default: author.name ↓ 

[author]                  # essential
  name = "_YA"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
