[de]
  languageCode = "de"
  lanq = "de"
  languageName = "Deutsche"
  weight = 1
  # contentDir = "de"
  # default_page_title = ""
  # default_page_subtitle = ""
  # description = ""

[en]
  languageCode = "en"
  lanq = "en"
  languageName = "English"
  weight = 2
  # contentDir = "en"
  # default_page_title = ""
  # default_page_subtitle = ""
  # description = ""