# config Main menu

# [[en.main]]
#   name = "HomeEN"
#   weight = 10
#   identifier = "homeEN"
#   url = "/en/"
# [[en.main]]
#   name = "ArchivesEN"
#   weight = 20
#   identifier = "archivesEN"
#   url = "/en/post/"
# [[en.main]]
#   name = "TagsEN"
#   weight = 30
#   identifier = "tagsEN"
#   url = "/en/tags/"
# [[en.main]]
#   name = "CategoriesEN"
#   weight = 40
#   identifier = "categoriesEN"
#   url = "/en/categories/"

# [[de.main]]
#   name = "Home"
#   weight = 10
#   identifier = "home"
#   url = "/de/"
# [[de.main]]
#   name = "Archives"
#   weight = 20
#   identifier = "archives"
#   url = "/de/post/"
# [[de.main]]
#   name = "Tags"
#   weight = 30
#   identifier = "tags"
#   url = "/de/tags/"
# [[de.main]]
#   name = "Categories"
#   weight = 40
#   identifier = "categories"
#   url = "/de/categories/"

# config Footer menu

# [[footer]]
#   name = "Contact"
#   weight = 10
#   identifier = "f-home"
#   url = "/"

# config MaiLaw footer menu
