homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
rssFullContent = true     # if false, Rss feed instead of the summary

# site info
logoTitle = "RMD Bau City"        # default: the title value
description = "RMD beta site"
logo = "images/logo.png"
since = "2012"            # Site creation time
phone = "+49 30 228 08 343"
fax = "+49 30 228 08 (fax)"
email = "info@rmd-citybau.de"
mapApiKey = "AIzaSyCVSQkQMnPD5A_Z9AzN6Frgei4oDgPfYAY"
mapFooterWidth = "100%"
mapFooterHeight = "200"
bodyBackGround = "images/mmpaper.svg"
headerBackGround = "images/whitewall.jpg"

[address]
  name = "RMD Bau City GmbH"
  street = "Arndtstraße 13"
  city = "10965 Berlin"

[opentime]
  workdays = "MO – FR"
  workhours = "08:00 – 20:00"

# The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
dateFormatToUse = "01.02.2006"

[social]
  a-email = "mailto:your@email.com"
  c-twitter = "http://localhost:1313"
  d-facebook = "http://localhost:1313"
  # e-linkedin = "http://localhost:1313"
  # g-github = "http://localhost:1313"
  # k-pocket = "http://localhost:1313"
  # l-tumblr = "http://localhost:1313"
  m-instagram = "http://localhost:1313"

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
customJS = []             # if ['custom.js'], load '/static/js/custom.js' file