name: github pages RMD

on:
  push:
    branches:
    - master

jobs:
  webpack-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Master checkout
      uses: actions/checkout@v2
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build with Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
      run: yarn
      # run: hugo --minify --cleanDestinationDir --gc
    - run: yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
